import json
from transformers import AutoTokenizer

def read_json(path):
    qa_data = []
    f = open(path, 'r', encoding='utf-8')
    for line in f.readlines():
        qa_data.append(json.loads(line))
    return qa_data

prompt_dict = {
    'qa': {
        'none': 'Answer the following question based on your internal knowledge with one or few words. Provide only one name, with no additional or irrelevant text.\nQuestion: {question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nAnswer: ',
    },
    'qa_cot': {
        'none': 'Answer the question by briefly explaining your reasoning with one or few sentences, then provide the final answer.\nQuestion: {question}{paras}{prediction}',
        'ra': '',
        'tail': '\nAnswer: ',
    },
    'qa_more': {
        'none': 'Generate 10 possible answers for the following question, each separated by a semicolon. These 10 answers must be different, and your response should be as concise as possible, with no irrelevant words beyond the answers.\nQuestion: {question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nAnswer: ',
    },
    'qa_extract': {
        'none': 'Here is the response generated by the model for this question. The response includes reasoning steps, making it difficult to locate the answer. Please extract the answer from the response without generating any other unrelated words. Do not generate conversational words.\nQuestion: {question}\nResponse: {prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nYour extracted answer: ',
    },
    'qa_prior': {
        'none': 'Please determine if you can accurately provide the answer to the question. If yes, reply with "certain", otherwise reply with "uncertain". Start your response with "certain" or "uncertain" and do not give any other words.\nQuestion: {question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nResponse: ',
    },
    'qa_post': {
        'none': 'Here is a question and the answer you provided. Please determine whether the answer is correct. If it is correct, respond with "certain." If it is incorrect, respond with "uncertain." Start your response with "certain" or "uncertain" and do not give any other words.\nQuestion: {question}{paras}{prediction}\nResponse: {prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nResponse: ',
    },
    'mc_qa': {
        'none': 'The following are multiple choice questions (with answers){subject}. Select the correct answer without any irrelevant words. Do not include conversational words and do not provide any explanation.\n\n{question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nAnswer: ',
    },
    'mc_qa_prior': {
        'none': 'Please determine if you can accurately select the correct answer to the question. If yes, reply with "certain", otherwise reply with "uncertain". Start your response with "certain" or "uncertain" and do not give any other words.\n\n{question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nResponse: ',
    },
    'mc_qa_post': {
        'none': 'Here is a question and the answer you select. Please determine whether the answer is correct. If it is correct, respond with "certain." If it is incorrect, respond with "uncertain." Start your response with "certain" or "uncertain" and do not give any other words.\nQuestion: {question}{paras}{prediction}\nResponse: {prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nResponse: ',
    },
    'mc_qa_cot': {
        'none': 'The following are multiple choice questions (with answers){subject}. Briefly explain your reasoning with one or few sentences and choose the correct answer. Start with "So, the correct answer is" to select the correct answer.\n\n{question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nAnswer: ',
    },
    'mc_qa_evidence': {
        'none': 'The following are multiple choice questions (with answers){subject}. Select the correct answer without any irrelevant words and explain why you choose this answer briefly.\n\n{question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words.\nQuestion: {question}{prediction}',
        'tail': '\nAnswer: ',
    },
    'qa_evidence': {
        'none': 'Answer the following question based on your internal knowledge with one or few words and explain why you give this answer briefly.\nQuestion: {question}{paras}{prediction}',
        'ra': 'Given the following information: \n{paras}\nAnswer the following question based on the given information or your internal knowledge with one or few words and explain why you give this answer.\nQuestion: {question}{prediction}',
        'tail': '\nAnswer: ',
    },
}

# 每个模型对应的 system prompt，apply_chat_template 会自动处理格式
MODEL_SYSTEM_PROMPT = {
    'llama2-7b-chat':       'You are a helpful assistant',
    'llama2-13b-chat':      'You are a helpful assistant',
    'llama3-8b-instruct':   'You are a helpful AI assistant for answering factual questions',
    'qwen2-7b-instruct':    'You are a helpful assistant.',
    'qwen2.5-7b-instruct':  'You are a helpful assistant.',
    'qwen2.5-14b-instruct': 'You are a helpful assistant.',
    'qwen2.5-32b-instruct': 'You are a helpful assistant.',
}


def _build_user_content(sample, args) -> str:
    """
    构建 user message 的纯文本内容（不含任何 chat template 标记）。
    逻辑与原 get_prompt 完全一致。
    """
    paras = ""
    ref_key = 'question'
    prompt = prompt_dict[args.type]['none']

    if args.ra != 'none':
        ra_dict = args.ra
        i = 0
        doc = []
        for k, v in ra_dict.items():
            v = min(v, len(sample[k]))
            for j in range(v):
                doc.append(("Passage-%d" % i) + sample[k][j])
                i += 1
        paras = '\n'.join(doc)
        prompt = prompt_dict[args.type]['ra']

    # usechat 模式下 tail 不需要（模型会自动接续），否则保留
    tail = prompt_dict[args.type]['tail'] if not args.usechat else ""
    prediction = sample['Res'] if 'post' in args.type else ""

    if args.task == 'mmlu' or args.task == 'tq':
        user_content = prompt.format(
            question=sample[ref_key], paras=paras,
            prediction=prediction, subject=args.subject,
        ) + tail
    else:
        user_content = prompt.format(
            question=sample[ref_key], paras=paras,
            prediction=prediction,
        ) + tail

    return user_content


def get_prompt(sample, args, tokenizer: AutoTokenizer) -> str:
    """
    单轮对话 prompt，使用 tokenizer.apply_chat_template 生成。
    替换原来手拼 model_template_dict 的方式。
    """
    system_prompt = MODEL_SYSTEM_PROMPT[args.model_name]
    user_content  = _build_user_content(sample, args)

    messages = [
        {"role": "system",  "content": system_prompt},
        {"role": "user",    "content": user_content},
    ]

    # add_generation_prompt=True 会在末尾追加模型开始生成的标记
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    return prompt


def get_prompt_for_multi_round(sample, args, tokenizer: AutoTokenizer) -> str:
    """
    多轮对话 prompt，使用 tokenizer.apply_chat_template 生成。
    替换原来手拼 model_template_dict_for_multi_round 的方式。

    原逻辑：
      - qa_post:          取 question[:2]（1问1答），再追加一轮判断
      - qa_post_multi_round: 取全部 question（多问多答），再追加一轮判断
    """
    system_prompt = MODEL_SYSTEM_PROMPT[args.model_name]

    # qa_post 只用前两轮（1问+1答）
    rounds = sample['question'][:2] if args.type == 'qa_post' else sample['question']

    # 把已有的 问/答 交替列表转成 messages 格式
    messages = [{"role": "system", "content": system_prompt}]
    for idx, turn in enumerate(rounds):
        role = "user" if idx % 2 == 0 else "assistant"
        messages.append({"role": role, "content": turn})

    # 追加最终判断轮
    judge_content = (
        f'Please determine whether your response [{rounds[1]}] contains the correct answer. '
        'If yes, respond with "certain." If it is incorrect, respond with "uncertain." '
        'Start your response with "certain" or "uncertain" and do not give any other words.'
    )
    messages.append({"role": "user", "content": judge_content})

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    return prompt


if __name__ == '__main__':
    from transformers import AutoTokenizer

    model_name = 'qwen2-7b-instruct'
    model_path  = '/path/to/your/model'   # 改成实际路径
    tokenizer   = AutoTokenizer.from_pretrained(model_path)

    base_dir = '/Users/shiyuni/Documents/research/project/datasets'
    dataset  = 'nq'
    mode     = 'test'
    out_path = f'{base_dir}/{dataset}/multi_round/{dataset}_{mode}_{model_name}.jsonl'
    data = read_json(out_path)

    # 验证：打印出来和手拼结果对比
    class FakeArgs:
        type        = 'qa_post'
        model_name  = model_name
        ra          = 'none'
        usechat     = True
        task        = 'nq'
        subject     = ''

    print(get_prompt_for_multi_round(data[0], FakeArgs(), tokenizer))